# Generated by Django 4.1.1 on 2022-09-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_point', models.JSONField()),
                ('route_type', models.CharField(choices=[('Car', 'Car'), ('Foot', 'Foot'), ('Motor', 'Motor')], default='Foot', max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=120)),
                ('description', models.TextField(null=True)),
                ('duration', models.IntegerField(default=7)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stop_route', to='route.place')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='start_route', to='route.place')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_admin', models.IntegerField()),
                ('approved_users', models.TextField(null=True)),
                ('pending_users', models.TextField(null=True)),
                ('start_date', models.DateField()),
                ('price', models.IntegerField(null=True)),
                ('id_route', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='route', to='route.route')),
            ],
        ),
    ]
