# Generated by Django 4.1.1 on 2022-10-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='stop_point',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='RouteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('id_route', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='route_review', to='route.route')),
            ],
        ),
    ]
