# Generated by Django 4.1.1 on 2022-10-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_route_stop_point_routereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='approved_users',
            new_name='event_users',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pending_users',
        ),
        migrations.AlterField(
            model_name='route',
            name='stop_point',
            field=models.TextField(null=True),
        ),
    ]
